#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v3
# autospec commit: 750e50d
#
Name     : perl-Getopt-Long-Descriptive
Version  : 0.114
Release  : 27
URL      : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Getopt-Long-Descriptive-0.114.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Getopt-Long-Descriptive-0.114.tar.gz
Summary  : 'Getopt::Long, but simpler and more powerful'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Getopt-Long-Descriptive-license = %{version}-%{release}
Requires: perl-Getopt-Long-Descriptive-perl = %{version}-%{release}
Requires: perl(File::Basename)
Requires: perl(Getopt::Long)
Requires: perl(List::Util)
Requires: perl(Params::Validate)
Requires: perl(Scalar::Util)
Requires: perl(Sub::Exporter)
BuildRequires : buildreq-cpan
BuildRequires : perl(CPAN::Meta::Check)
BuildRequires : perl(Data::OptList)
BuildRequires : perl(Module::Implementation)
BuildRequires : perl(Params::Util)
BuildRequires : perl(Params::Validate)
BuildRequires : perl(Sub::Exporter)
BuildRequires : perl(Sub::Exporter::Util)
BuildRequires : perl(Sub::Install)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Test::Warnings)
BuildRequires : perl(Try::Tiny)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This archive contains the distribution Getopt-Long-Descriptive,
version 0.114:
Getopt::Long, but simpler and more powerful

%package dev
Summary: dev components for the perl-Getopt-Long-Descriptive package.
Group: Development
Provides: perl-Getopt-Long-Descriptive-devel = %{version}-%{release}
Requires: perl-Getopt-Long-Descriptive = %{version}-%{release}

%description dev
dev components for the perl-Getopt-Long-Descriptive package.


%package license
Summary: license components for the perl-Getopt-Long-Descriptive package.
Group: Default

%description license
license components for the perl-Getopt-Long-Descriptive package.


%package perl
Summary: perl components for the perl-Getopt-Long-Descriptive package.
Group: Default
Requires: perl-Getopt-Long-Descriptive = %{version}-%{release}

%description perl
perl components for the perl-Getopt-Long-Descriptive package.


%prep
%setup -q -n Getopt-Long-Descriptive-0.114
cd %{_builddir}/Getopt-Long-Descriptive-0.114
pushd ..
cp -a Getopt-Long-Descriptive-0.114 buildavx2
popd
pushd ..
cp -a Getopt-Long-Descriptive-0.114 buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Getopt-Long-Descriptive
cp %{_builddir}/Getopt-Long-Descriptive-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Getopt-Long-Descriptive/0edd7bb71da7095da485bbfd14c8eb3c70309f7b || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Getopt::Long::Descriptive.3
/usr/share/man/man3/Getopt::Long::Descriptive::Opts.3
/usr/share/man/man3/Getopt::Long::Descriptive::Usage.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Getopt-Long-Descriptive/0edd7bb71da7095da485bbfd14c8eb3c70309f7b

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
