#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Getopt-Long-Descriptive
Version  : 0.109
Release  : 14
URL      : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Getopt-Long-Descriptive-0.109.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Getopt-Long-Descriptive-0.109.tar.gz
Summary  : 'Getopt::Long, but simpler and more powerful'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Getopt-Long-Descriptive-license = %{version}-%{release}
Requires: perl-Getopt-Long-Descriptive-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(CPAN::Meta::Check)
BuildRequires : perl(Data::OptList)
BuildRequires : perl(Module::Implementation)
BuildRequires : perl(Params::Util)
BuildRequires : perl(Params::Validate)
BuildRequires : perl(Sub::Exporter)
BuildRequires : perl(Sub::Exporter::Util)
BuildRequires : perl(Sub::Install)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Test::Warnings)
BuildRequires : perl(Try::Tiny)

%description
This archive contains the distribution Getopt-Long-Descriptive,
version 0.109:
Getopt::Long, but simpler and more powerful

%package dev
Summary: dev components for the perl-Getopt-Long-Descriptive package.
Group: Development
Provides: perl-Getopt-Long-Descriptive-devel = %{version}-%{release}
Requires: perl-Getopt-Long-Descriptive = %{version}-%{release}

%description dev
dev components for the perl-Getopt-Long-Descriptive package.


%package license
Summary: license components for the perl-Getopt-Long-Descriptive package.
Group: Default

%description license
license components for the perl-Getopt-Long-Descriptive package.


%package perl
Summary: perl components for the perl-Getopt-Long-Descriptive package.
Group: Default
Requires: perl-Getopt-Long-Descriptive = %{version}-%{release}

%description perl
perl components for the perl-Getopt-Long-Descriptive package.


%prep
%setup -q -n Getopt-Long-Descriptive-0.109
cd %{_builddir}/Getopt-Long-Descriptive-0.109

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Getopt-Long-Descriptive
cp %{_builddir}/Getopt-Long-Descriptive-0.109/LICENSE %{buildroot}/usr/share/package-licenses/perl-Getopt-Long-Descriptive/8b5e17836ab3a81ac7330abf4b518c85786ad172
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Getopt::Long::Descriptive.3
/usr/share/man/man3/Getopt::Long::Descriptive::Opts.3
/usr/share/man/man3/Getopt::Long::Descriptive::Usage.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Getopt-Long-Descriptive/8b5e17836ab3a81ac7330abf4b518c85786ad172

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/Getopt/Long/Descriptive.pm
/usr/lib/perl5/vendor_perl/5.34.0/Getopt/Long/Descriptive/Opts.pm
/usr/lib/perl5/vendor_perl/5.34.0/Getopt/Long/Descriptive/Usage.pm
